"""Typed OPSD-Flow inputs and Student-owned denoising trajectories."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import torch


@dataclass(frozen=True)
class ActionConditioning:
    """Fast-WAM conditioning with images separated from other modalities."""

    input_image: torch.Tensor
    prompt: str | None = None
    proprio: torch.Tensor | None = None
    context: torch.Tensor | None = None
    context_mask: torch.Tensor | None = None

    def __post_init__(self) -> None:
        has_prompt = self.prompt is not None
        has_context = self.context is not None or self.context_mask is not None
        if has_prompt == has_context:
            raise ValueError("Provide either prompt or context/context_mask, but not both.")
        if has_context and (self.context is None or self.context_mask is None):
            raise ValueError("context and context_mask must be provided together.")


@dataclass(frozen=True)
class StudentDenoisingStep:
    """One immutable latent state generated by the Student policy."""

    latent: torch.Tensor
    timestep: torch.Tensor
    delta_sigma: torch.Tensor


@dataclass(frozen=True)
class StudentTrajectory:
    """A complete Student action trajectory that the Teacher may only score."""

    steps: tuple[StudentDenoisingStep, ...]
    final_action: torch.Tensor
    metadata: dict[str, Any]

    @classmethod
    def from_inference_result(
        cls,
        result: dict[str, Any],
        *,
        expected_steps: int,
        metadata: dict[str, Any] | None = None,
    ) -> StudentTrajectory:
        trace = result.get("denoising_trace")
        if not isinstance(trace, list):
            raise ValueError("Fast-WAM result does not contain a denoising trace.")
        if len(trace) != int(expected_steps):
            raise ValueError(
                f"Denoising trace has {len(trace)} steps; expected {expected_steps}."
            )
        steps = tuple(
            StudentDenoisingStep(
                latent=item["latent"].detach(),
                timestep=item["timestep"].detach(),
                delta_sigma=item["delta_sigma"].detach(),
            )
            for item in trace
        )
        final_action = result["action"].detach()
        return cls(steps=steps, final_action=final_action, metadata=dict(metadata or {}))
